# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "auctionhouse"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Chen"]
  s.date = "2012-07-14"
  s.description = "Generates out a fully functional set of models, controllers, views, specs, and migrations for an operational auction site much like ebay or the millions of flash-sales sites out there. Currently in development."
  s.email = "foxnewsnetwork@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/auctionhouse.rb",
    "lib/auctionhouse/generators.rb",
    "lib/auctionhouse/tasks.rb",
    "lib/generators/auctionhouse/README.markdown",
    "lib/generators/auctionhouse/USAGE",
    "lib/generators/auctionhouse/auctionhouse_generator.rb",
    "lib/generators/auctionhouse/templates/controllers/bids_controller.rb",
    "lib/generators/auctionhouse/templates/controllers/items_controller.rb",
    "lib/generators/auctionhouse/templates/migrations/migration.rb",
    "lib/generators/auctionhouse/templates/models/bid.rb",
    "lib/generators/auctionhouse/templates/models/item.rb",
    "spec/auctionhouse_spec.rb",
    "test/helper.rb",
    "test/test_auctionhouse.rb"
  ]
  s.homepage = "http://github.com/foxnewsnetwork/auctionhouse"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Simple macro used to generate out an online-auction platform. Currently in development."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

